Repository autopkg/apizz-recipes, pull requests merged in 2020-07, with the labels that each got.

#24 Update Autodesk Maya recipe
  Autodesk/AutodeskMaya2020Import.munki.recipe
Labels: bug, enhancement

#25 Added version to package name
  TeamViewer/TeamViewerHostCustom.pkg.recipe
Labels: update

#27 Add SwiftDefaultApps recipes
  SwiftDefaultApps/SwiftDefaultApps.download.recipe
  SwiftDefaultApps/SwiftDefaultApps.munki.recipe
  SwiftDefaultApps/SwiftDefaultApps.pkg.recipe
  SwiftDefaultApps/SwiftDefaultApps_CLI.munki.recipe
  SwiftDefaultApps/SwiftDefaultApps_CLI.pkg.recipe
Labels: enhancement
